name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [7.2.0]
        ruby: [3.2, 3.3]
        include:
          - ruby: 3.3
            rails_version: 7.1.3.4
          - ruby: 3.2
            rails_version: 7.0.8.4
          - ruby: 3.1
            rails_version: 6.1.7.8
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies with Rails ${{ matrix.rails_version }}
        run: bundle install
      - name: Run tests
        run: bundle exec rake
